import React, { useState } from "react";
import {
  ActivityIndicator,
  Alert,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";
import { Feather } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { API_BASE_URL } from "@/constants/api";
import { useAuth } from "@/context/AuthContext";

const MAIN_SUPER_ADMIN_MOBILE = "8554994735";

function cleanMobile(value: string) {
  return value.replace(/\D/g, "").slice(0, 10);
}

function cleanAccessId(value: string) {
  return value.trim().toUpperCase();
}

function apiUrl(path: string) {
  const base = API_BASE_URL.replace(/\/$/, "");
  const cleanPath = path.startsWith("/") ? path : `/${path}`;
  return `${base}${cleanPath}`;
}

async function readJson(res: Response) {
  const text = await res.text();

  if (!text) return {};

  try {
    return JSON.parse(text);
  } catch {
    return {
      success: false,
      message: text,
    };
  }
}

export default function SuperAdminLoginScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { login } = useAuth();

  const [mobile, setMobile] = useState("");
  const [accessId, setAccessId] = useState("");
  const [submitting, setSubmitting] = useState(false);

  const finalMobile = cleanMobile(mobile);
  const isMainSuperAdmin = finalMobile === MAIN_SUPER_ADMIN_MOBILE;

  const handleLogin = async () => {
    const finalAccessId = cleanAccessId(accessId);

    if (finalMobile.length !== 10) {
      Alert.alert("Mobile required", "Enter a valid 10 digit mobile number.");
      return;
    }

    if (!isMainSuperAdmin && !finalAccessId) {
      Alert.alert(
        "Unique ID required",
        "Enter the unique access ID generated by the main super admin.",
      );
      return;
    }

    try {
      setSubmitting(true);

      if (isMainSuperAdmin) {
        await login({
          id: "SUPER_ADMIN_TEJASHREE",
          name: "Tejashree Ma'am",
          mobile: MAIN_SUPER_ADMIN_MOBILE,
          role: "super_admin",
          ward: "All Wards",
          wardCode: null,
          isSuperAdmin: true,
          nagarsevakId: "SUPER_ADMIN_TEJASHREE",
          avatarColor: "#16A34A",
          createdAt: new Date().toISOString(),
        });

        router.replace("/super-admin" as any);
        return;
      }

      const res = await fetch(apiUrl("/api/auth/super-admin-access-login"), {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          mobile: finalMobile,
          accessCode: finalAccessId,
        }),
      });

      const data = await readJson(res);

      if (!res.ok || !data.success || !data.user) {
        throw new Error(
          data.message ||
            data.error ||
            "Invalid mobile number or unique access ID.",
        );
      }

      await login({
        id: String(data.user.id || `SAUSER_${finalMobile}`),
        name: String(data.user.name || "Super Admin"),
        mobile: finalMobile,
        role: "super_admin",
        ward: "All Wards",
        wardCode: null,
        isSuperAdmin: true,
        nagarsevakId: String(data.user.id || `SAUSER_${finalMobile}`),
        avatarColor: "#16A34A",
        createdAt: new Date().toISOString(),
      });

      router.replace("/super-admin" as any);
    } catch (e: any) {
      Alert.alert(
        "Login failed",
        e?.message ||
          "Could not verify super admin access. Check the mobile number and unique ID.",
      );
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <View style={styles.root}>
      <LinearGradient
        colors={["#020617", "#052E16", "#064E3B", "#047857"]}
        locations={[0, 0.38, 0.72, 1]}
        style={StyleSheet.absoluteFill}
      />

      <View style={styles.glowTop} />
      <View style={styles.glowBottom} />

      <KeyboardAvoidingView
        style={styles.flex}
        behavior={Platform.OS === "ios" ? "padding" : undefined}
      >
        <ScrollView
          style={styles.flex}
          contentContainerStyle={[
            styles.content,
            {
              paddingTop: insets.top + 14,
              paddingBottom: insets.bottom + 30,
            },
          ]}
          keyboardShouldPersistTaps="handled"
          showsVerticalScrollIndicator={false}
        >
          <View style={styles.topBar}>
            <TouchableOpacity
              style={styles.backBtn}
              onPress={() => router.replace("/secret-access" as any)}
              activeOpacity={0.85}
            >
              <Feather name="chevron-left" size={22} color="#ECFDF5" />
            </TouchableOpacity>

            <View style={styles.secureBadge}>
              <View style={styles.liveDot} />
              <Text style={styles.secureBadgeText}>ADMIN ACCESS</Text>
            </View>
          </View>

          <View style={styles.hero}>
            <View style={styles.adminMarkOuter}>
              <View style={styles.adminMark}>
                <Feather name="shield" size={34} color="#047857" />
              </View>
            </View>

            <Text style={styles.kicker}>Connect T Control Center</Text>
            <Text style={styles.title}>Super Admin Login</Text>
            <Text style={styles.subtitle}>
              Protected dashboard for city-wide access, officer control,
              alerts, jobs and civic operations.
            </Text>
          </View>

          <View style={styles.securityPanel}>
            <View style={styles.panelHeader}>
              <View>
                <Text style={styles.panelTitle}>Identity Verification</Text>
                <Text style={styles.panelSub}>
                  Enter authorized mobile number to continue.
                </Text>
              </View>
              <View style={styles.panelIcon}>
                <Feather name="lock" size={18} color="#047857" />
              </View>
            </View>

            <View style={styles.inputBlock}>
              <Text style={styles.label}>Authorized Mobile Number</Text>
              <View style={styles.inputShell}>
                <View style={styles.inputPrefix}>
                  <Text style={styles.inputPrefixText}>+91</Text>
                </View>
                <TextInput
                  value={mobile}
                  onChangeText={(value) => setMobile(cleanMobile(value))}
                  placeholder="8554994735"
                  placeholderTextColor="#94A3B8"
                  keyboardType="number-pad"
                  maxLength={10}
                  style={styles.input}
                />
                {finalMobile.length === 10 && (
                  <Feather
                    name={isMainSuperAdmin ? "check-circle" : "key"}
                    size={18}
                    color={isMainSuperAdmin ? "#059669" : "#D97706"}
                  />
                )}
              </View>
            </View>

            {!isMainSuperAdmin && (
              <View style={styles.inputBlock}>
                <Text style={styles.label}>Unique Access ID</Text>
                <View style={styles.inputShell}>
                  <View style={styles.inputPrefix}>
                    <Feather name="key" size={14} color="#64748B" />
                  </View>
                  <TextInput
                    value={accessId}
                    onChangeText={(value) => setAccessId(cleanAccessId(value))}
                    placeholder="Example: SA-ABC123"
                    placeholderTextColor="#94A3B8"
                    autoCapitalize="characters"
                    style={styles.input}
                  />
                </View>
              </View>
            )}

            <View
              style={[
                styles.statusBox,
                isMainSuperAdmin ? styles.statusBoxSuccess : styles.statusBoxNeutral,
              ]}
            >
              <View
                style={[
                  styles.statusIcon,
                  isMainSuperAdmin
                    ? { backgroundColor: "#D1FAE5" }
                    : { backgroundColor: "#FEF3C7" },
                ]}
              >
                <Feather
                  name={isMainSuperAdmin ? "user-check" : "key"}
                  size={16}
                  color={isMainSuperAdmin ? "#059669" : "#D97706"}
                />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={styles.statusTitle}>
                  {isMainSuperAdmin
                    ? "Main Super Admin detected"
                    : "Access code required"}
                </Text>
                <Text style={styles.statusText}>
                  {isMainSuperAdmin
                    ? "This number is allowed to open the full Super Admin dashboard."
                    : "Only users with a unique ID generated by the main super admin can continue."}
                </Text>
              </View>
            </View>

            <TouchableOpacity
              style={[styles.primaryBtn, submitting && styles.disabledBtn]}
              onPress={handleLogin}
              disabled={submitting}
              activeOpacity={0.88}
            >
              <LinearGradient
                colors={
                  submitting
                    ? ["#94A3B8", "#64748B"]
                    : ["#047857", "#059669", "#10B981"]
                }
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 1 }}
                style={styles.primaryGradient}
              >
                {submitting ? (
                  <ActivityIndicator color="white" />
                ) : (
                  <>
                    <Feather name="log-in" size={17} color="white" />
                    <Text style={styles.primaryBtnText}>Open Super Admin Dashboard</Text>
                  </>
                )}
              </LinearGradient>
            </TouchableOpacity>
          </View>

          <View style={styles.rulesCard}>
            <View style={styles.rulesHeader}>
              <Feather name="alert-triangle" size={15} color="#FDE68A" />
              <Text style={styles.rulesTitle}>Restricted Area</Text>
            </View>
            <Text style={styles.rulesText}>
              This login is not for citizens or officers. Unauthorized access
              attempts should be denied by backend verification.
            </Text>
          </View>

          <Text style={styles.footer}>CONNECT T · SECURE ADMIN PORTAL</Text>
        </ScrollView>
      </KeyboardAvoidingView>
    </View>
  );
}

const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  root: {
    flex: 1,
    backgroundColor: "#020617",
  },
  glowTop: {
    position: "absolute",
    top: -80,
    right: -60,
    width: 210,
    height: 210,
    borderRadius: 105,
    backgroundColor: "rgba(16,185,129,0.18)",
  },
  glowBottom: {
    position: "absolute",
    bottom: 50,
    left: -90,
    width: 230,
    height: 230,
    borderRadius: 115,
    backgroundColor: "rgba(34,197,94,0.12)",
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 20,
  },
  topBar: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  secureBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.10)",
    borderRadius: 999,
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#6EE7B7",
  },
  secureBadgeText: {
    fontSize: 10,
    color: "#ECFDF5",
    fontFamily: "Inter_800ExtraBold",
    letterSpacing: 1,
  },
  hero: {
    alignItems: "center",
    paddingTop: 45,
    paddingBottom: 24,
  },
  adminMarkOuter: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: "rgba(255,255,255,0.10)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    marginBottom: 18,
  },
  adminMark: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.24,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  kicker: {
    fontSize: 11,
    color: "#A7F3D0",
    fontFamily: "Inter_800ExtraBold",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: 7,
  },
  title: {
    fontSize: 30,
    color: "white",
    fontFamily: "Inter_800ExtraBold",
    fontWeight: "900",
    letterSpacing: -0.7,
    textAlign: "center",
  },
  subtitle: {
    marginTop: 9,
    fontSize: 13,
    lineHeight: 20,
    color: "rgba(236,253,245,0.74)",
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    paddingHorizontal: 6,
  },
  securityPanel: {
    backgroundColor: "white",
    borderRadius: 30,
    padding: 18,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 12,
  },
  panelHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 18,
  },
  panelTitle: {
    fontSize: 20,
    color: "#0F172A",
    fontFamily: "Inter_800ExtraBold",
    fontWeight: "900",
    letterSpacing: -0.35,
  },
  panelSub: {
    marginTop: 3,
    fontSize: 12,
    color: "#64748B",
    fontFamily: "Inter_400Regular",
  },
  panelIcon: {
    width: 42,
    height: 42,
    borderRadius: 16,
    backgroundColor: "#ECFDF5",
    alignItems: "center",
    justifyContent: "center",
  },
  inputBlock: {
    marginBottom: 14,
  },
  label: {
    fontSize: 12,
    color: "#334155",
    fontFamily: "Inter_800ExtraBold",
    marginBottom: 8,
  },
  inputShell: {
    minHeight: 54,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  inputPrefix: {
    minWidth: 36,
    height: 30,
    borderRadius: 12,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  inputPrefixText: {
    fontSize: 12,
    color: "#475569",
    fontFamily: "Inter_800ExtraBold",
  },
  input: {
    flex: 1,
    fontSize: 15,
    color: "#0F172A",
    fontFamily: "Inter_600SemiBold",
    paddingVertical: 0,
  },
  statusBox: {
    marginTop: 2,
    borderRadius: 20,
    padding: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderWidth: 1,
  },
  statusBoxSuccess: {
    backgroundColor: "#ECFDF5",
    borderColor: "#A7F3D0",
  },
  statusBoxNeutral: {
    backgroundColor: "#FFFBEB",
    borderColor: "#FDE68A",
  },
  statusIcon: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  statusTitle: {
    fontSize: 13,
    color: "#0F172A",
    fontFamily: "Inter_800ExtraBold",
    fontWeight: "900",
  },
  statusText: {
    marginTop: 2,
    fontSize: 11,
    color: "#64748B",
    fontFamily: "Inter_400Regular",
    lineHeight: 16,
  },
  primaryBtn: {
    marginTop: 18,
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#047857",
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  disabledBtn: {
    opacity: 0.72,
  },
  primaryGradient: {
    minHeight: 54,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    paddingHorizontal: 16,
  },
  primaryBtnText: {
    color: "white",
    fontSize: 14,
    fontFamily: "Inter_800ExtraBold",
    fontWeight: "900",
  },
  rulesCard: {
    marginTop: 16,
    borderRadius: 22,
    padding: 15,
    backgroundColor: "rgba(15,23,42,0.36)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  rulesHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 7,
  },
  rulesTitle: {
    fontSize: 12,
    color: "#FEF3C7",
    fontFamily: "Inter_800ExtraBold",
    letterSpacing: 0.4,
  },
  rulesText: {
    fontSize: 11,
    lineHeight: 17,
    color: "rgba(236,253,245,0.68)",
    fontFamily: "Inter_400Regular",
  },
  footer: {
    marginTop: "auto",
    paddingTop: 28,
    textAlign: "center",
    fontSize: 10,
    color: "rgba(236,253,245,0.42)",
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 2,
  },
});
