import React, { useState } from "react";
import {
  ActivityIndicator,
  Alert,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";
import { Feather } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import TopShade from "@/components/TopShade";
import { API_BASE_URL } from "@/constants/api";
import { useAuth } from "@/context/AuthContext";

const MAIN_SUPER_ADMIN_MOBILE = "8554994735";

function cleanMobile(value: string) {
  return value.replace(/\D/g, "").slice(0, 10);
}

function cleanAccessId(value: string) {
  return value.trim().toUpperCase();
}

function apiUrl(path: string) {
  const base = API_BASE_URL.replace(/\/$/, "");
  const cleanPath = path.startsWith("/") ? path : `/${path}`;
  return `${base}${cleanPath}`;
}

async function readJson(res: Response) {
  const text = await res.text();

  if (!text) return {};

  try {
    return JSON.parse(text);
  } catch {
    return {
      success: false,
      message: text,
    };
  }
}

export default function SuperAdminLoginScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { login } = useAuth();

  const [mobile, setMobile] = useState("");
  const [accessId, setAccessId] = useState("");
  const [submitting, setSubmitting] = useState(false);

  const isMainSuperAdmin = cleanMobile(mobile) === MAIN_SUPER_ADMIN_MOBILE;

  const handleLogin = async () => {
    const finalMobile = cleanMobile(mobile);
    const finalAccessId = cleanAccessId(accessId);

    if (finalMobile.length !== 10) {
      Alert.alert("Mobile required", "Enter a valid 10 digit mobile number.");
      return;
    }

    if (!isMainSuperAdmin && !finalAccessId) {
      Alert.alert(
        "Unique ID required",
        "Enter the unique access ID generated by the main super admin.",
      );
      return;
    }

    try {
      setSubmitting(true);

      if (isMainSuperAdmin) {
        await login({
          id: "SUPER_ADMIN_TEJASHREE",
          name: "Tejashree Ma'am",
          mobile: MAIN_SUPER_ADMIN_MOBILE,
          role: "super_admin",
          ward: "All Wards",
          wardCode: null,
          isSuperAdmin: true,
          nagarsevakId: "SUPER_ADMIN_TEJASHREE",
          avatarColor: "#16A34A",
          createdAt: new Date().toISOString(),
        });

        router.replace("/super-admin" as any);
        return;
      }

      const res = await fetch(apiUrl("/api/auth/super-admin-access-login"), {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          mobile: finalMobile,
          accessCode: finalAccessId,
        }),
      });

      const data = await readJson(res);

      if (!res.ok || !data.success || !data.user) {
        throw new Error(
          data.message ||
            data.error ||
            "Invalid mobile number or unique access ID.",
        );
      }

      await login({
        id: String(data.user.id || `SAUSER_${finalMobile}`),
        name: String(data.user.name || "Super Admin"),
        mobile: finalMobile,
        role: "super_admin",
        ward: "All Wards",
        wardCode: null,
        isSuperAdmin: true,
        nagarsevakId: String(data.user.id || `SAUSER_${finalMobile}`),
        avatarColor: "#16A34A",
        createdAt: new Date().toISOString(),
      });

      router.replace("/super-admin" as any);
    } catch (e: any) {
      Alert.alert(
        "Login failed",
        e?.message ||
          "Could not verify super admin access. Check the mobile number and unique ID.",
      );
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <View style={styles.root}>
      <LinearGradient
        colors={["#052E16", "#166534", "#16A34A"]}
        locations={[0, 0.52, 1]}
        style={StyleSheet.absoluteFill}
      />

      <TopShade height={220} />

      <KeyboardAvoidingView
        style={styles.flex}
        behavior={Platform.OS === "ios" ? "padding" : undefined}
      >
        <ScrollView
          style={styles.flex}
          contentContainerStyle={[
            styles.content,
            {
              paddingTop: insets.top + 16,
              paddingBottom: insets.bottom + 32,
            },
          ]}
          keyboardShouldPersistTaps="handled"
          showsVerticalScrollIndicator={false}
        >
          <View style={styles.header}>
            <TouchableOpacity
              style={styles.backBtn}
              onPress={() => router.replace("/secret-access" as any)}
              activeOpacity={0.85}
            >
              <Feather name="chevron-left" size={22} color="#16A34A" />
            </TouchableOpacity>

            <View style={styles.secureBadge}>
              <Feather name="shield" size={11} color="#6EE7B7" />
              <Text style={styles.secureBadgeText}>Secure Login</Text>
            </View>
          </View>

          <View style={styles.hero}>
            <View style={styles.heroIcon}>
              <Feather name="user-check" size={34} color="#16A34A" />
            </View>

            <Text style={styles.title}>Super Admin Login</Text>
            <Text style={styles.subtitle}>
              Main access is restricted to Tejashree Ma'am. Additional admins
              require a unique ID.
            </Text>
          </View>

          <View style={styles.card}>
            <Text style={styles.label}>Mobile Number</Text>
            <TextInput
              value={mobile}
              onChangeText={(value) => setMobile(cleanMobile(value))}
              placeholder="Enter 10 digit mobile number"
              placeholderTextColor="#94A3B8"
              keyboardType="number-pad"
              maxLength={10}
              style={styles.input}
            />

            {!isMainSuperAdmin && (
              <>
                <Text style={styles.label}>Unique Access ID</Text>
                <TextInput
                  value={accessId}
                  onChangeText={(value) => setAccessId(cleanAccessId(value))}
                  placeholder="Example: SA-ABC123"
                  placeholderTextColor="#94A3B8"
                  autoCapitalize="characters"
                  style={styles.input}
                />
              </>
            )}

            {isMainSuperAdmin ? (
              <View style={styles.infoBox}>
                <Feather name="check-circle" size={16} color="#16A34A" />
                <Text style={styles.infoText}>
                  Main super admin number detected.
                </Text>
              </View>
            ) : (
              <View style={styles.infoBox}>
                <Feather name="key" size={16} color="#16A34A" />
                <Text style={styles.infoText}>
                  Enter the unique ID generated from Super Admin Settings.
                </Text>
              </View>
            )}

            <TouchableOpacity
              style={[styles.primaryBtn, submitting && styles.disabledBtn]}
              onPress={handleLogin}
              disabled={submitting}
              activeOpacity={0.86}
            >
              {submitting ? (
                <ActivityIndicator color="white" />
              ) : (
                <>
                  <Feather name="log-in" size={17} color="white" />
                  <Text style={styles.primaryBtnText}>Open Dashboard</Text>
                </>
              )}
            </TouchableOpacity>
          </View>

          <Text style={styles.footer}>CONNECT T SUPER ADMIN ACCESS</Text>
        </ScrollView>
      </KeyboardAvoidingView>
    </View>
  );
}

const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  root: {
    flex: 1,
    backgroundColor: "#16A34A",
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 22,
  },
  header: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
  },
  secureBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: "rgba(255,255,255,0.14)",
    borderRadius: 999,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  secureBadgeText: {
    fontSize: 11,
    color: "white",
    fontFamily: "Inter_700Bold",
  },
  hero: {
    alignItems: "center",
    paddingTop: 52,
    paddingBottom: 28,
  },
  heroIcon: {
    width: 82,
    height: 82,
    borderRadius: 41,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 18,
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  title: {
    fontSize: 29,
    color: "white",
    fontFamily: "Inter_700Bold",
    fontWeight: "900",
    letterSpacing: -0.5,
    textAlign: "center",
  },
  subtitle: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 19,
    color: "rgba(255,255,255,0.78)",
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    paddingHorizontal: 10,
  },
  card: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 18,
    shadowColor: "#0F172A",
    shadowOpacity: 0.14,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  label: {
    fontSize: 12,
    color: "#475569",
    fontFamily: "Inter_700Bold",
    marginBottom: 7,
    marginTop: 10,
  },
  input: {
    height: 50,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 14,
    fontSize: 14,
    color: "#0F172A",
    fontFamily: "Inter_500Medium",
  },
  infoBox: {
    marginTop: 14,
    borderRadius: 16,
    backgroundColor: "#F0FDF4",
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  infoText: {
    flex: 1,
    fontSize: 11,
    lineHeight: 16,
    color: "#166534",
    fontFamily: "Inter_600SemiBold",
  },
  primaryBtn: {
    height: 52,
    borderRadius: 18,
    backgroundColor: "#16A34A",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    marginTop: 18,
  },
  disabledBtn: {
    opacity: 0.65,
  },
  primaryBtnText: {
    color: "white",
    fontSize: 15,
    fontFamily: "Inter_700Bold",
  },
  footer: {
    marginTop: "auto",
    paddingTop: 28,
    textAlign: "center",
    fontSize: 10,
    color: "rgba(255,255,255,0.4)",
    fontFamily: "Inter_400Regular",
    letterSpacing: 2,
  },
});
