import { Feather } from "@expo/vector-icons";
import { useGlobalSearchParams, useRouter, useSegments } from "expo-router";
import React, { useEffect, useRef } from "react";
import { Image, Linking, Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";

import { AppBroadcast, useBroadcasts } from "@/context/BroadcastContext";

const ORANGE = "#EA580C";
const GREEN = "#16A34A";
function categoryMeta(category: AppBroadcast["category"]) {
  if (category === "emergency") return { label: "Emergency", icon: "alert-triangle" as const, color: "#B91C1C", bg: "#FEE2E2" };
  if (category === "information") return { label: "Information", icon: "info" as const, color: "#1D4ED8", bg: "#DBEAFE" };
  if (category === "notice") return { label: "Notice", icon: "file-text" as const, color: "#6D28D9", bg: "#EDE9FE" };
  return { label: "Announcement", icon: "radio" as const, color: "#B45309", bg: "#FEF3C7" };
}
function BroadcastDetailModal({ item, onClose }: { item: AppBroadcast | null; onClose: () => void }) {
  if (!item) return null; const meta = categoryMeta(item.category);
  return <Modal visible transparent animationType="fade" onRequestClose={onClose}><View style={styles.modalBackdrop} accessibilityViewIsModal><View style={styles.modalCard}><View style={styles.modalHeader}><View style={[styles.modalIcon, { backgroundColor: meta.bg }]}><Feather name={item.mediaType === "video" ? "play-circle" : item.mediaType === "image" ? "image" : meta.icon} size={24} color={meta.color} /></View><View style={styles.modalHeaderCopy}><Text style={[styles.modalType, { color: meta.color }]}>{meta.label}</Text><Text style={styles.modalDate}>{new Date(item.sentAt || item.createdAt).toLocaleString("en-IN")}</Text></View><TouchableOpacity style={styles.closeIcon} onPress={onClose}><Feather name="x" size={20} color="#64748B" /></TouchableOpacity></View><ScrollView style={styles.modalScroll} contentContainerStyle={styles.modalContent} showsVerticalScrollIndicator={false}><Text style={styles.modalTitle}>{item.title}</Text><Text style={styles.modalBody}>{item.body}</Text>{item.mediaType === "image" && item.mediaUri ? <Image source={{ uri: item.mediaUri }} style={styles.fullImage} resizeMode="contain" /> : null}{item.mediaType === "video" && item.mediaUri ? <TouchableOpacity style={styles.playButton} onPress={() => void Linking.openURL(item.mediaUri!)}><Feather name="play-circle" size={22} color="white" /><Text style={styles.playText}>Play attached video</Text>{item.mediaDurationSeconds ? <Text style={styles.durationText}>{Math.ceil(item.mediaDurationSeconds / 60)} min</Text> : null}</TouchableOpacity> : null}<View style={styles.metaRow}><View style={styles.metaPill}><Feather name="users" size={12} color="#64748B" /><Text style={styles.metaText}>{item.ward || "All citizens"}</Text></View><View style={styles.metaPill}><Feather name="user" size={12} color="#64748B" /><Text style={styles.metaText}>{item.createdByName || "Connect-T"}</Text></View></View></ScrollView><TouchableOpacity style={styles.doneButton} onPress={onClose}><Text style={styles.doneText}>Back to News</Text></TouchableOpacity></View></View></Modal>;
}
export default function CivicBroadcastExperience() {
  const router = useRouter(); const segments = useSegments(); const params = useGlobalSearchParams<{ broadcastId?: string | string[] }>(); const { broadcasts, refreshBroadcasts, markBroadcastRead } = useBroadcasts(); const openedReadId = useRef<string | null>(null);
  const requestedId = Array.isArray(params.broadcastId) ? params.broadcastId[0] : params.broadcastId; const selectedBroadcast = requestedId ? broadcasts.find((item) => item.id === requestedId && item.status === "sent") || null : null; const firstSegment = String(segments[0] || ""); const secondSegment = String(segments[1] || ""); const isCitizenNewsTab = firstSegment === "(tabs)" && secondSegment === "feed"; const isLegacyNewsRoute = firstSegment === "alert" && secondSegment === "list"; const isNewsRoute = isCitizenNewsTab || isLegacyNewsRoute;
  useEffect(() => { if (requestedId && !selectedBroadcast) void refreshBroadcasts().catch(() => undefined); }, [refreshBroadcasts, requestedId, selectedBroadcast]);
  useEffect(() => { if (!selectedBroadcast || selectedBroadcast.isRead || openedReadId.current === selectedBroadcast.id) return; openedReadId.current = selectedBroadcast.id; void markBroadcastRead(selectedBroadcast.id).catch(() => { openedReadId.current = null; }); }, [markBroadcastRead, selectedBroadcast]);
  const closeBroadcast = () => { if (isCitizenNewsTab) router.replace("/(tabs)/feed" as any); else router.replace("/alert/list" as any); };
  return <BroadcastDetailModal item={isNewsRoute ? selectedBroadcast : null} onClose={closeBroadcast} />;
}
const styles = StyleSheet.create({
  modalBackdrop: { flex: 1, alignItems: "center", justifyContent: "center", padding: 18, backgroundColor: "rgba(15,23,42,0.66)" }, modalCard: { width: "100%", maxWidth: 520, maxHeight: "92%", borderRadius: 24, backgroundColor: "white", padding: 18 }, modalHeader: { flexDirection: "row", alignItems: "center", gap: 10 }, modalIcon: { width: 48, height: 48, borderRadius: 16, alignItems: "center", justifyContent: "center" }, modalHeaderCopy: { flex: 1 }, modalType: { fontSize: 10, textTransform: "uppercase", letterSpacing: 0.8, fontFamily: "Inter_700Bold" }, modalDate: { marginTop: 3, color: "#94A3B8", fontSize: 9.5, fontFamily: "Inter_400Regular" }, closeIcon: { width: 42, height: 42, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#F8FAFC" }, modalScroll: { marginTop: 14 }, modalContent: { paddingBottom: 10 }, modalTitle: { color: "#0F172A", fontSize: 21, lineHeight: 28, fontFamily: "Inter_700Bold" }, modalBody: { marginTop: 10, color: "#475569", fontSize: 13, lineHeight: 21, fontFamily: "Inter_400Regular" }, fullImage: { marginTop: 14, width: "100%", height: 300, borderRadius: 16, backgroundColor: "#F8FAFC" }, playButton: { marginTop: 14, minHeight: 54, borderRadius: 15, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: ORANGE }, playText: { color: "white", fontSize: 12.5, fontFamily: "Inter_700Bold" }, durationText: { marginLeft: "auto", color: "rgba(255,255,255,0.82)", fontSize: 10, fontFamily: "Inter_600SemiBold" }, metaRow: { marginTop: 14, flexDirection: "row", flexWrap: "wrap", gap: 7 }, metaPill: { flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 9, paddingVertical: 7, borderRadius: 10, backgroundColor: "#F8FAFC" }, metaText: { color: "#64748B", fontSize: 10, fontFamily: "Inter_600SemiBold" }, doneButton: { marginTop: 14, minHeight: 48, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: GREEN }, doneText: { color: "white", fontSize: 12.5, fontFamily: "Inter_700Bold" },
});
