import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

export type Language = "en" | "hi" | "mr";

export interface LanguageOption {
  code: Language;
  label: string;
  nativeLabel: string;
}

export const languageOptions: LanguageOption[] = [
  { code: "en", label: "English", nativeLabel: "English" },
  { code: "hi", label: "Hindi", nativeLabel: "हिन्दी" },
  { code: "mr", label: "Marathi", nativeLabel: "मराठी" },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    citizen: "Citizen",
    nagarsevak: "Nagarsevak",
    admin: "Admin",
    reportProblem: "Report an Issue",
    reportProblemSub: "Click photo → Ward officer resolves it",
    active: "Active",
    resolved: "Resolved",
    community: "News",
    feed: "News",
    panel: "Panel",
    admin: "Admin",
    officer: "Officer",
    alertsAndNews: "Alerts & News",
    alerts: "Alerts",
    live: "LIVE",
    recentComplaints: "Recent Complaints",
    viewAll: "View All",
    tapToReport: "Tap to report your first problem",
    utilityStatus: "Utility Status",
    quickServices: "Quick Services",
    allServices: "All Services",
    emergencyContacts: "Emergency Contacts",
    waterSupply: "Water Supply",
    electricity: "Electricity",
    hospitals: "Hospitals",
    childCare: "Child Care",
    clinics: "Clinics",
    police: "Police",
    banks: "Banks",
    postOffice: "Post Office",
    schools: "Schools",
    crematorium: "Crematorium",
    nearbyServices: "Nearby Services",
    ambernath: "Ambernath",
    complaints: "Complaints",
    newComplaint: "New Complaint",
    myComplaints: "My Complaints",
    communityFeed: "Community Feed",
    profile: "Profile",
    emergency: "Emergency",
    sos: "SOS",
    home: "Home",
    welcome: "Welcome",
    enterMobile: "Enter your mobile number to login or register",
    continue: "Continue",
    selectRole: "Select Your Role",
    selectRoleSub: "How would you like to use Connect T?",
    completeProfile: "Complete Your Profile",
    fullName: "Full Name",
    age: "Age",
    email: "Email",
    phone: "Phone",
    address: "Address",
    memberSince: "Member Since",
    complainantProfile: "Complainant Profile",
    citizen: "Citizen",
    close: "Close",
    wardLocation: "Ward / Location",
    selectWard: "Select your ward",
    register: "Register & Continue",
    required: "Required",
    optional: "Optional",
    welcomeBack: "Welcome back!",
    loginAs: "Login as",
    differentNumber: "Use different number",
    logout: "Logout",
    logoutConfirm: "Are you sure you want to logout from Connect T?",
    cancel: "Cancel",
    yesLogout: "Yes, Logout",
    quickActions: "QUICK ACTIONS",
    viewTrackComplaints: "View and track all complaints",
    clickPhotoRaise: "Click a photo and raise complaint",
    wardUpdates: "Ward updates & announcements",
    quickAccessHelp: "Quick access to help numbers",
    accountDetails: "ACCOUNT DETAILS",
    usefulLinks: "USEFUL LINKS",
    loginSignUp: "Login / Sign Up",
    loginToAccess: "Login to access your profile",
    welcomeToConnectT: "Welcome to Connect T",
    language: "Language",
    changeLanguage: "Change Language",
    selectLanguage: "Select Language",
    poweredBy: "Powered by Connect T",
    citizenPlatform: "Citizen Services Platform",
    getStarted: "Get Started",
    tapToContinue: "Tap to continue",
    alert: "Alert",
    news: "News",
    bedAvailability: "Bed Availability",
    totalBeds: "Total Beds",
    occupied: "Occupied",
    available: "Available",
    servicesProvided: "Services Provided",
    contactNumbers: "Contact Numbers",
    recentReviews: "Recent Reviews",
    reviews: "reviews",
    call: "Call",
    moreContacts: "more contacts — Tap to view all details",
    bedsFree: "beds free",
    hoursDay: "Hours/day",
    reduced: "Reduced",
    normal: "Normal",
    submitted: "Submitted",
    assigned: "Assigned",
    inProgress: "In Progress",
    rejected: "Rejected",
    fullNameReq: "Full Name",
    mobile: "Mobile",
    ward: "Ward",
    role: "Role",
    total: "Total",
    goBack: "Go Back",
    placeNotFound: "Place not found",
    nagarsevakPanel: "Nagarsevak Panel",
    nagarsevakDashboard: "Nagarsevak Panel",
    wardComplaintsDesc: "View & resolve ward complaints",
    viewResolveWard: "View & resolve ward complaints",
    reportProblemAction: "Report Issue",
    ulmcUpdate: "AMC Update",
    waterRestricted: "Water supply restricted in Station Area East — 8AM to 2PM today",
    sortedByDistance: "Sorted by distance",
    nearYou: "near you",
    totalWard: "total · Ward",
    new: "New",
    done: "Done",
    noComplaintsYet: "No complaints yet",
    tapNewToRaise: 'Tap "New" to raise your first complaint',
    emergencySOS: "Emergency SOS",
    tapToCallSOS: "Tap to call National Emergency Number 112",
    allEmergencyNumbers: "ALL EMERGENCY NUMBERS",
    emergencyTips: "Emergency Tips",
    nearestHospital: "Nearest Hospital",
    callNow: "Call Now",
    tip1: "Stay calm and describe your exact location",
    tip2: "Call 112 for all emergencies in India",
    tip3: "Keep your Aadhaar number ready for hospitals",
    tip4: "Note your area's ward number for AMC calls",
    oneTopAccess: "One-tap access to all emergency services",
    wardUpdatesAlerts: "Ward updates, alerts & complaints",
    post: "Post",
    updates: "Updates",
    noActiveComplaints: "No Active Complaints",
    allResolved: "All complaints have been resolved!",
    noResolvedComplaints: "No Resolved Complaints",
    resolvedAppearHere: "Resolved complaints will appear here",
    shareWithWard: "Share something with your ward...",
    newPost: "New Post",
    postType: "POST TYPE",
    content: "CONTENT",
    shareWithCommunity: "Share with the community...",
    announcement: "Announcement",
    update: "Update",
    issue: "Issue",
    general: "General",
    pinnedPost: "Pinned Post",
    details: "Details",
    roads: "Roads",
    water: "Water",
    garbage: "Garbage",
    drainage: "Drainage",
    streetLight: "Street Light",
    encroachment: "Encroachment",
    other: "Other",
    updateComplaint: "Update Complaint",
    selectAction: "SELECT ACTION",
    assignToTeam: "Assign to Team",
    reject: "Reject",
    markInProgress: "Mark In Progress",
    markResolved: "Mark Resolved",
    noteResolution: "NOTE / RESOLUTION (optional)",
    addNoteForCitizen: "Add a note for the citizen...",
    updateStatus: "Update Status",
    pending: "Pending",
    needsAttention: "need your attention",
    noComplaintsInCategory: "No complaints in this category",
    allWards: "All Wards",
    fullControl: "Ward Complaints",
    officersTab: "Officers",
    servicesTab: "Services",
    complaintsTab: "Complaints",
    nagarsevakPerformance: "Nagarsevak Performance",
    serviceManagement: "Service Management",
    addService: "Add Service",
    servicesListed: "services listed",
    allStatus: "All Status",
    noComplaintsFound: "No complaints found",
    adminLoginRequired: "Admin Login Required",
    adminLoginDesc: "This panel is for Nagarsevaks only.",
    loginAsAdmin: "Login as Admin",
    reportProblemTitle: "Report an Issue",
    yourComplaintGoes: "Your complaint goes directly to ward officer",
    photoOfProblem: "PHOTO OF PROBLEM",
    takePhoto: "Take Photo",
    clickPhotoOfProblem: "Click a photo of the problem",
    chooseFromGallery: "Choose from Gallery",
    retake: "Retake",
    complaintCategory: "COMPLAINT CATEGORY",
    complaintTitle: "COMPLAINT TITLE",
    titlePlaceholder: "e.g. Large pothole on main road",
    description: "DESCRIPTION",
    descriptionPlaceholder: "Describe the problem in detail — location, severity, how long it has been there...",
    location: "LOCATION",
    enterExactLocation: "Enter exact location",
    autoDetected: "auto-detected",
    complaintNotice: "Your complaint will be assigned to the ward officer within 24 hours. You will receive status updates here.",
    submitComplaint: "Submit Complaint",
    selectCategoryAlert: "Select Category",
    selectCategoryMsg: "Please select a complaint category.",
    addTitleAlert: "Add Title",
    addTitleMsg: "Please add a brief title for your complaint.",
    addDescAlert: "Add Description",
    addDescMsg: "Please describe the problem.",
    permissionNeeded: "Permission needed",
    cameraPermission: "Camera access is required to take a photo of the problem.",
    complaintRegistered: "Complaint Registered!",
    complaintStatus: "Complaint Status",
    complaintDetails: "Complaint Details",
    category: "Category",
    submittedOn: "Submitted On",
    assignedTo: "Assigned To",
    activityTimeline: "Activity Timeline",
    problemPhoto: "Problem Photo",
    complaintNotFound: "Complaint not found",
    issueResolved: "Issue resolved",
    policeStations: "Police Stations",
    banksATMs: "Banks & ATMs",
    postOffices: "Post Offices",
    crematoriums: "Crematoriums",
    updated: "Updated",
    enterFullName: "Enter your full name",
    enterValidAge: "Enter a valid age (1–120)",
    enterValidEmail: "Enter a valid email address",
    enterAddress: "Enter your address",
    enterValidPhone: "Enter a valid 10-digit phone number",
    selectWardError: "Please select your ward",
    enterOtp: "Enter 4-digit OTP",
    otpVerification: "OTP Verification",
    otpSent: "OTP sent to",
    otpHint: "Use any 4 digits for demo",
    verifyOtp: "Verify OTP",
    phoneVerified: "Phone Verified!",
    allowNotifications: "How would you like to receive updates?",
    emailNotifications: "Email Notifications",
    emailNotifDesc: "Receive complaint updates via email",
    whatsappNotifications: "WhatsApp Notifications",
    whatsappNotifDesc: "Get updates on WhatsApp",
    registerBtn: "Register",
    loginBtn: "Login",
    registrationSuccess: "Registration Successful!",
    registrationFailed: "Registration failed. Try again.",
    redirectingHome: "Redirecting to home...",
    invalidNagarsevakId: "Invalid Nagarsevak ID",
    accountNotFound: "Account not found. Please register first.",
    nagarsevakIdLabel: "Nagarsevak ID",
    nagarsevakIdPlaceholder: "e.g. NS001",
    nagarsevakIdHelp: "Enter your Nagarsevak ID to access the officer panel",
    currentAddress: "Address",
    phoneNumber: "Phone Number",
    enterPhoneNumber: "Enter phone number",
    enterAge: "Enter age",
    nagarsevakOnly: "Nagarsevak Access Only",
    nagarsevakOnlyDesc: "This panel is for Nagarsevaks only. Login with your Nagarsevak ID to access.",
  },
  hi: {
    goodMorning: "सुप्रभात",
    goodAfternoon: "नमस्कार",
    goodEvening: "शुभ संध्या",
    citizen: "नागरिक",
    nagarsevak: "नगरसेवक",
    admin: "प्रशासक",
    reportProblem: "समस्या दर्ज करें",
    reportProblemSub: "फोटो क्लिक करें → वार्ड अधिकारी हल करेंगे",
    active: "सक्रिय",
    resolved: "हल किया",
    community: "समाचार",
    feed: "समाचार",
    panel: "पैनल",
    admin: "प्रशासक",
    officer: "अधिकारी",
    alertsAndNews: "सूचनाएं और समाचार",
    alerts: "सूचनाएं",
    live: "लाइव",
    recentComplaints: "हाल की शिकायतें",
    viewAll: "सभी देखें",
    tapToReport: "अपनी पहली समस्या दर्ज करने के लिए टैप करें",
    utilityStatus: "सेवा स्थिति",
    quickServices: "त्वरित सेवाएं",
    allServices: "सभी सेवाएं",
    emergencyContacts: "आपातकालीन संपर्क",
    waterSupply: "जल आपूर्ति",
    electricity: "बिजली",
    hospitals: "अस्पताल",
    childCare: "बाल चिकित्सा",
    clinics: "क्लिनिक",
    police: "पुलिस",
    banks: "बैंक",
    postOffice: "डाकघर",
    schools: "विद्यालय",
    crematorium: "शमशानभूमि",
    nearbyServices: "नजदीकी सेवाएं",
    ambernath: "उल्हासनगर",
    complaints: "शिकायतें",
    newComplaint: "नई शिकायत",
    myComplaints: "मेरी शिकायतें",
    communityFeed: "समुदाय फ़ीड",
    profile: "प्रोफ़ाइल",
    emergency: "आपातकालीन",
    sos: "एसओएस",
    home: "होम",
    welcome: "स्वागत है",
    enterMobile: "लॉगिन या रजिस्टर करने के लिए अपना मोबाइल नंबर दर्ज करें",
    continue: "जारी रखें",
    selectRole: "अपनी भूमिका चुनें",
    selectRoleSub: "आप Connect T का उपयोग कैसे करना चाहते हैं?",
    completeProfile: "अपनी प्रोफ़ाइल पूरी करें",
    fullName: "पूरा नाम",
    age: "उम्र",
    email: "ईमेल",
    phone: "फ़ोन",
    address: "पता",
    memberSince: "सदस्य तिथि",
    complainantProfile: "शिकायतकर्ता प्रोफ़ाइल",
    citizen: "नागरिक",
    close: "बंद करें",
    wardLocation: "वार्ड / स्थान",
    selectWard: "अपना वार्ड चुनें",
    register: "रजिस्टर करें और जारी रखें",
    required: "आवश्यक",
    optional: "वैकल्पिक",
    welcomeBack: "वापसी पर स्वागत है!",
    loginAs: "लॉगिन करें",
    differentNumber: "अलग नंबर उपयोग करें",
    logout: "लॉगआउट",
    logoutConfirm: "क्या आप Connect T से लॉगआउट करना चाहते हैं?",
    cancel: "रद्द करें",
    yesLogout: "हां, लॉगआउट",
    quickActions: "त्वरित कार्य",
    viewTrackComplaints: "सभी शिकायतें देखें और ट्रैक करें",
    clickPhotoRaise: "फोटो क्लिक करें और शिकायत दर्ज करें",
    wardUpdates: "वार्ड अपडेट और घोषणाएं",
    quickAccessHelp: "सहायता नंबर तक तेज़ पहुंच",
    accountDetails: "खाता विवरण",
    usefulLinks: "उपयोगी लिंक",
    loginSignUp: "लॉगिन / साइन अप",
    loginToAccess: "प्रोफ़ाइल एक्सेस करने के लिए लॉगिन करें",
    welcomeToConnectT: "Connect T में स्वागत है",
    language: "भाषा",
    changeLanguage: "भाषा बदलें",
    selectLanguage: "भाषा चुनें",
    poweredBy: "Powered by Connect T",
    citizenPlatform: "नागरिक सेवा मंच",
    getStarted: "शुरू करें",
    tapToContinue: "जारी रखने के लिए टैप करें",
    alert: "सूचना",
    news: "समाचार",
    bedAvailability: "बेड उपलब्धता",
    totalBeds: "कुल बेड",
    occupied: "भरे हुए",
    available: "उपलब्ध",
    servicesProvided: "उपलब्ध सेवाएं",
    contactNumbers: "संपर्क नंबर",
    recentReviews: "हाल की समीक्षाएं",
    reviews: "समीक्षाएं",
    call: "कॉल",
    moreContacts: "और संपर्क — सभी विवरण देखने के लिए टैप करें",
    bedsFree: "बेड उपलब्ध",
    hoursDay: "घंटे/दिन",
    reduced: "कम",
    normal: "सामान्य",
    submitted: "जमा किया",
    assigned: "सौंपा गया",
    inProgress: "प्रगति में",
    rejected: "अस्वीकृत",
    fullNameReq: "पूरा नाम",
    mobile: "मोबाइल",
    ward: "वार्ड",
    role: "भूमिका",
    total: "कुल",
    goBack: "वापस जाएं",
    placeNotFound: "स्थान नहीं मिला",
    nagarsevakPanel: "नगरसेवक पैनल",
    nagarsevakDashboard: "नगरसेवक पैनल",
    wardComplaintsDesc: "वार्ड शिकायतें देखें और हल करें",
    viewResolveWard: "वार्ड शिकायतें देखें और हल करें",
    reportProblemAction: "समस्या दर्ज करें",
    ulmcUpdate: "AMC अपडेट",
    waterRestricted: "स्टेशन एरिया ईस्ट में जल आपूर्ति प्रतिबंधित — आज सुबह 8 से दोपहर 2 बजे तक",
    sortedByDistance: "दूरी के अनुसार",
    nearYou: "आपके पास",
    totalWard: "कुल · वार्ड",
    new: "नया",
    done: "पूर्ण",
    noComplaintsYet: "अभी कोई शिकायत नहीं",
    tapNewToRaise: 'अपनी पहली शिकायत दर्ज करने के लिए "नया" टैप करें',
    emergencySOS: "आपातकालीन SOS",
    tapToCallSOS: "राष्ट्रीय आपातकालीन नंबर 112 पर कॉल करने के लिए टैप करें",
    allEmergencyNumbers: "सभी आपातकालीन नंबर",
    emergencyTips: "आपातकालीन सुझाव",
    nearestHospital: "निकटतम अस्पताल",
    callNow: "अभी कॉल करें",
    tip1: "शांत रहें और अपना सटीक स्थान बताएं",
    tip2: "भारत में सभी आपातकालीन स्थितियों के लिए 112 कॉल करें",
    tip3: "अस्पतालों के लिए अपना आधार नंबर तैयार रखें",
    tip4: "AMC कॉल के लिए अपने क्षेत्र का वार्ड नंबर नोट करें",
    oneTopAccess: "सभी आपातकालीन सेवाओं तक एक टैप एक्सेस",
    wardUpdatesAlerts: "वार्ड अपडेट, सूचनाएं और शिकायतें",
    post: "पोस्ट",
    updates: "अपडेट",
    noActiveComplaints: "कोई सक्रिय शिकायत नहीं",
    allResolved: "सभी शिकायतें हल हो गई हैं!",
    noResolvedComplaints: "कोई हल की गई शिकायत नहीं",
    resolvedAppearHere: "हल की गई शिकायतें यहां दिखाई देंगी",
    shareWithWard: "अपने वार्ड के साथ कुछ साझा करें...",
    newPost: "नई पोस्ट",
    postType: "पोस्ट प्रकार",
    content: "सामग्री",
    shareWithCommunity: "समुदाय के साथ साझा करें...",
    announcement: "घोषणा",
    update: "अपडेट",
    issue: "समस्या",
    general: "सामान्य",
    pinnedPost: "पिन की गई पोस्ट",
    details: "विवरण",
    roads: "सड़कें",
    water: "पानी",
    garbage: "कचरा",
    drainage: "नालियां",
    streetLight: "स्ट्रीट लाइट",
    encroachment: "अतिक्रमण",
    other: "अन्य",
    updateComplaint: "शिकायत अपडेट करें",
    selectAction: "कार्रवाई चुनें",
    assignToTeam: "टीम को सौंपें",
    reject: "अस्वीकार करें",
    markInProgress: "प्रगति में चिह्नित करें",
    markResolved: "हल किया चिह्नित करें",
    noteResolution: "नोट / समाधान (वैकल्पिक)",
    addNoteForCitizen: "नागरिक के लिए एक नोट जोड़ें...",
    updateStatus: "स्थिति अपडेट करें",
    pending: "लंबित",
    needsAttention: "आपके ध्यान की आवश्यकता है",
    noComplaintsInCategory: "इस श्रेणी में कोई शिकायत नहीं",
    allWards: "सभी वार्ड",
    fullControl: "वार्ड शिकायतें",
    officersTab: "अधिकारी",
    servicesTab: "सेवाएं",
    complaintsTab: "शिकायतें",
    nagarsevakPerformance: "नगरसेवक प्रदर्शन",
    serviceManagement: "सेवा प्रबंधन",
    addService: "सेवा जोड़ें",
    servicesListed: "सेवाएं सूचीबद्ध",
    allStatus: "सभी स्थिति",
    noComplaintsFound: "कोई शिकायत नहीं मिली",
    adminLoginRequired: "प्रशासक लॉगिन आवश्यक",
    adminLoginDesc: "यह पैनल केवल नगरसेवकों के लिए है।",
    loginAsAdmin: "प्रशासक के रूप में लॉगिन करें",
    reportProblemTitle: "समस्या दर्ज करें",
    yourComplaintGoes: "आपकी शिकायत सीधे वार्ड अधिकारी को जाती है",
    photoOfProblem: "समस्या की तस्वीर",
    takePhoto: "फोटो लें",
    clickPhotoOfProblem: "समस्या की फोटो क्लिक करें",
    chooseFromGallery: "गैलरी से चुनें",
    retake: "दोबारा लें",
    complaintCategory: "शिकायत श्रेणी",
    complaintTitle: "शिकायत शीर्षक",
    titlePlaceholder: "जैसे: मुख्य सड़क पर बड़ा गड्ढा",
    description: "विवरण",
    descriptionPlaceholder: "समस्या का विस्तार से वर्णन करें — स्थान, गंभीरता, कब से है...",
    location: "स्थान",
    enterExactLocation: "सटीक स्थान दर्ज करें",
    autoDetected: "स्वतः पता लगाया",
    complaintNotice: "आपकी शिकायत 24 घंटे के भीतर वार्ड अधिकारी को सौंपी जाएगी। आपको यहां स्थिति अपडेट मिलेंगे।",
    submitComplaint: "शिकायत जमा करें",
    selectCategoryAlert: "श्रेणी चुनें",
    selectCategoryMsg: "कृपया शिकायत श्रेणी चुनें।",
    addTitleAlert: "शीर्षक जोड़ें",
    addTitleMsg: "कृपया अपनी शिकायत के लिए एक संक्षिप्त शीर्षक जोड़ें।",
    addDescAlert: "विवरण जोड़ें",
    addDescMsg: "कृपया समस्या का वर्णन करें।",
    permissionNeeded: "अनुमति आवश्यक",
    cameraPermission: "समस्या की फोटो लेने के लिए कैमरा एक्सेस आवश्यक है।",
    complaintRegistered: "शिकायत दर्ज हो गई!",
    complaintStatus: "शिकायत स्थिति",
    complaintDetails: "शिकायत विवरण",
    category: "श्रेणी",
    submittedOn: "जमा करने की तारीख",
    assignedTo: "को सौंपा गया",
    activityTimeline: "गतिविधि टाइमलाइन",
    problemPhoto: "समस्या की तस्वीर",
    complaintNotFound: "शिकायत नहीं मिली",
    issueResolved: "समस्या हल हो गई",
    policeStations: "पुलिस स्टेशन",
    banksATMs: "बैंक और ATM",
    postOffices: "डाकघर",
    crematoriums: "शमशानभूमि",
    updated: "अपडेटेड",
    enterFullName: "अपना पूरा नाम दर्ज करें",
    enterValidAge: "वैध उम्र दर्ज करें (1–120)",
    enterValidEmail: "वैध ईमेल पता दर्ज करें",
    enterAddress: "अपना पता दर्ज करें",
    enterValidPhone: "वैध 10-अंकीय फोन नंबर दर्ज करें",
    selectWardError: "कृपया अपना वार्ड चुनें",
    enterOtp: "4-अंकीय OTP दर्ज करें",
    otpVerification: "OTP सत्यापन",
    otpSent: "OTP भेजा गया",
    otpHint: "डेमो के लिए कोई भी 4 अंक उपयोग करें",
    verifyOtp: "OTP सत्यापित करें",
    phoneVerified: "फोन सत्यापित!",
    allowNotifications: "आप अपडेट कैसे प्राप्त करना चाहते हैं?",
    emailNotifications: "ईमेल सूचनाएं",
    emailNotifDesc: "ईमेल द्वारा शिकायत अपडेट प्राप्त करें",
    whatsappNotifications: "WhatsApp सूचनाएं",
    whatsappNotifDesc: "WhatsApp पर अपडेट प्राप्त करें",
    registerBtn: "रजिस्टर करें",
    loginBtn: "लॉगिन",
    registrationSuccess: "पंजीकरण सफल!",
    registrationFailed: "पंजीकरण विफल। पुनः प्रयास करें।",
    redirectingHome: "होम पर जा रहे हैं...",
    invalidNagarsevakId: "अमान्य नगरसेवक ID",
    accountNotFound: "खाता नहीं मिला। कृपया पहले रजिस्टर करें।",
    nagarsevakIdLabel: "नगरसेवक ID",
    nagarsevakIdPlaceholder: "जैसे NS001",
    nagarsevakIdHelp: "अधिकारी पैनल तक पहुंचने के लिए अपना नगरसेवक ID दर्ज करें",
    currentAddress: "पता",
    phoneNumber: "फोन नंबर",
    enterPhoneNumber: "फोन नंबर दर्ज करें",
    enterAge: "उम्र दर्ज करें",
    nagarsevakOnly: "केवल नगरसेवक पहुंच",
    nagarsevakOnlyDesc: "यह पैनल केवल नगरसेवकों के लिए है। पहुंच के लिए अपना नगरसेवक ID से लॉगिन करें।",
  },
  mr: {
    goodMorning: "सुप्रभात",
    goodAfternoon: "नमस्कार",
    goodEvening: "शुभ संध्याकाळ",
    citizen: "नागरिक",
    nagarsevak: "नगरसेवक",
    admin: "प्रशासक",
    reportProblem: "समस्या नोंदवा",
    reportProblemSub: "फोटो काढा → वॉर्ड अधिकारी सोडवतील",
    active: "सक्रिय",
    resolved: "सोडवले",
    community: "बातम्या",
    feed: "बातम्या",
    panel: "पॅनेल",
    admin: "प्रशासक",
    officer: "अधिकारी",
    alertsAndNews: "सूचना आणि बातम्या",
    alerts: "सूचना",
    live: "लाइव्ह",
    recentComplaints: "अलीकडील तक्रारी",
    viewAll: "सर्व पहा",
    tapToReport: "तुमची पहिली समस्या नोंदवण्यासाठी टॅप करा",
    utilityStatus: "सेवा स्थिती",
    quickServices: "जलद सेवा",
    allServices: "सर्व सेवा",
    emergencyContacts: "आणीबाणी संपर्क",
    waterSupply: "पाणीपुरवठा",
    electricity: "वीज",
    hospitals: "रुग्णालये",
    childCare: "बालरोग",
    clinics: "दवाखाने",
    police: "पोलीस",
    banks: "बँका",
    postOffice: "टपालघर",
    schools: "शाळा",
    crematorium: "शमशानभूमी",
    nearbyServices: "जवळपासच्या सेवा",
    ambernath: "उल्हासनगर",
    complaints: "तक्रारी",
    newComplaint: "नवीन तक्रार",
    myComplaints: "माझ्या तक्रारी",
    communityFeed: "समुदाय फीड",
    profile: "प्रोफाइल",
    emergency: "आणीबाणी",
    sos: "एसओएस",
    home: "होम",
    welcome: "स्वागत",
    enterMobile: "लॉगिन किंवा नोंदणी करण्यासाठी तुमचा मोबाइल नंबर टाका",
    continue: "पुढे जा",
    selectRole: "तुमची भूमिका निवडा",
    selectRoleSub: "तुम्हाला Connect T कसे वापरायचे आहे?",
    completeProfile: "तुमचे प्रोफाइल पूर्ण करा",
    fullName: "पूर्ण नाव",
    age: "वय",
    email: "ईमेल",
    phone: "फोन",
    address: "पत्ता",
    memberSince: "सदस्यत्व तारीख",
    complainantProfile: "तक्रारदाराची माहिती",
    citizen: "नागरिक",
    close: "बंद करा",
    wardLocation: "वॉर्ड / ठिकाण",
    selectWard: "तुमचा वॉर्ड निवडा",
    register: "नोंदणी करा आणि पुढे जा",
    required: "आवश्यक",
    optional: "ऐच्छिक",
    welcomeBack: "पुन्हा स्वागत!",
    loginAs: "म्हणून लॉगिन करा",
    differentNumber: "वेगळा नंबर वापरा",
    logout: "लॉगआउट",
    logoutConfirm: "तुम्हाला Connect T मधून लॉगआउट करायचे आहे का?",
    cancel: "रद्द करा",
    yesLogout: "हो, लॉगआउट",
    quickActions: "जलद कार्ये",
    viewTrackComplaints: "सर्व तक्रारी पहा आणि ट्रॅक करा",
    clickPhotoRaise: "फोटो काढा आणि तक्रार नोंदवा",
    wardUpdates: "वॉर्ड अपडेट आणि घोषणा",
    quickAccessHelp: "मदत क्रमांकांना जलद प्रवेश",
    accountDetails: "खाते तपशील",
    usefulLinks: "उपयुक्त लिंक",
    loginSignUp: "लॉगिन / साइन अप",
    loginToAccess: "प्रोफाइल पाहण्यासाठी लॉगिन करा",
    welcomeToConnectT: "Connect T मध्ये स्वागत",
    language: "भाषा",
    changeLanguage: "भाषा बदला",
    selectLanguage: "भाषा निवडा",
    poweredBy: "Powered by Connect T",
    citizenPlatform: "नागरिक सेवा व्यासपीठ",
    getStarted: "सुरू करा",
    tapToContinue: "पुढे जाण्यासाठी टॅप करा",
    alert: "सूचना",
    news: "बातमी",
    bedAvailability: "बेड उपलब्धता",
    totalBeds: "एकूण बेड",
    occupied: "भरलेले",
    available: "उपलब्ध",
    servicesProvided: "उपलब्ध सेवा",
    contactNumbers: "संपर्क क्रमांक",
    recentReviews: "अलीकडील पुनरावलोकने",
    reviews: "पुनरावलोकने",
    call: "कॉल",
    moreContacts: "आणखी संपर्क — सर्व तपशील पाहण्यासाठी टॅप करा",
    bedsFree: "बेड उपलब्ध",
    hoursDay: "तास/दिवस",
    reduced: "कमी",
    normal: "सामान्य",
    submitted: "सबमिट केले",
    assigned: "नियुक्त",
    inProgress: "प्रगतीत",
    rejected: "नाकारले",
    fullNameReq: "पूर्ण नाव",
    mobile: "मोबाइल",
    ward: "वॉर्ड",
    role: "भूमिका",
    total: "एकूण",
    goBack: "मागे जा",
    placeNotFound: "ठिकाण सापडले नाही",
    nagarsevakPanel: "नगरसेवक पॅनेल",
    nagarsevakDashboard: "नगरसेवक पॅनेल",
    wardComplaintsDesc: "वॉर्ड तक्रारी पहा आणि सोडवा",
    viewResolveWard: "वॉर्ड तक्रारी पहा आणि सोडवा",
    reportProblemAction: "समस्या नोंदवा",
    ulmcUpdate: "AMC अपडेट",
    waterRestricted: "स्टेशन एरिया ईस्ट मध्ये पाणीपुरवठा प्रतिबंधित — आज सकाळी 8 ते दुपारी 2 पर्यंत",
    sortedByDistance: "अंतरानुसार",
    nearYou: "तुमच्या जवळ",
    totalWard: "एकूण · वॉर्ड",
    new: "नवीन",
    done: "पूर्ण",
    noComplaintsYet: "अद्याप तक्रार नाही",
    tapNewToRaise: 'तुमची पहिली तक्रार नोंदवण्यासाठी "नवीन" टॅप करा',
    emergencySOS: "आणीबाणी SOS",
    tapToCallSOS: "राष्ट्रीय आणीबाणी क्रमांक 112 वर कॉल करण्यासाठी टॅप करा",
    allEmergencyNumbers: "सर्व आणीबाणी क्रमांक",
    emergencyTips: "आणीबाणी टिप्स",
    nearestHospital: "जवळचे रुग्णालय",
    callNow: "आता कॉल करा",
    tip1: "शांत रहा आणि तुमचे नेमके ठिकाण सांगा",
    tip2: "भारतातील सर्व आणीबाणीसाठी 112 कॉल करा",
    tip3: "रुग्णालयांसाठी तुमचा आधार क्रमांक तयार ठेवा",
    tip4: "AMC कॉलसाठी तुमच्या भागाचा वॉर्ड क्रमांक नोट करा",
    oneTopAccess: "सर्व आणीबाणी सेवांना एक टॅप एक्सेस",
    wardUpdatesAlerts: "वॉर्ड अपडेट, सूचना आणि तक्रारी",
    post: "पोस्ट",
    updates: "अपडेट्स",
    noActiveComplaints: "सक्रिय तक्रारी नाहीत",
    allResolved: "सर्व तक्रारी सोडवल्या गेल्या आहेत!",
    noResolvedComplaints: "सोडवलेल्या तक्रारी नाहीत",
    resolvedAppearHere: "सोडवलेल्या तक्रारी येथे दिसतील",
    shareWithWard: "तुमच्या वॉर्डशी काहीतरी शेअर करा...",
    newPost: "नवीन पोस्ट",
    postType: "पोस्ट प्रकार",
    content: "मजकूर",
    shareWithCommunity: "समुदायासोबत शेअर करा...",
    announcement: "घोषणा",
    update: "अपडेट",
    issue: "समस्या",
    general: "सामान्य",
    pinnedPost: "पिन केलेली पोस्ट",
    details: "तपशील",
    roads: "रस्ते",
    water: "पाणी",
    garbage: "कचरा",
    drainage: "गटारी",
    streetLight: "स्ट्रीट लाइट",
    encroachment: "अतिक्रमण",
    other: "इतर",
    updateComplaint: "तक्रार अपडेट करा",
    selectAction: "कृती निवडा",
    assignToTeam: "टीमला सोपवा",
    reject: "नाकारा",
    markInProgress: "प्रगतीत चिन्हांकित करा",
    markResolved: "सोडवले चिन्हांकित करा",
    noteResolution: "नोट / निराकरण (ऐच्छिक)",
    addNoteForCitizen: "नागरिकासाठी नोट जोडा...",
    updateStatus: "स्थिती अपडेट करा",
    pending: "प्रलंबित",
    needsAttention: "तुमच्या लक्षाची गरज आहे",
    noComplaintsInCategory: "या श्रेणीत तक्रारी नाहीत",
    allWards: "सर्व वॉर्ड",
    fullControl: "वॉर्ड तक्रारी",
    officersTab: "अधिकारी",
    servicesTab: "सेवा",
    complaintsTab: "तक्रारी",
    nagarsevakPerformance: "नगरसेवक कामगिरी",
    serviceManagement: "सेवा व्यवस्थापन",
    addService: "सेवा जोडा",
    servicesListed: "सेवा सूचीबद्ध",
    allStatus: "सर्व स्थिती",
    noComplaintsFound: "तक्रारी सापडल्या नाहीत",
    adminLoginRequired: "प्रशासक लॉगिन आवश्यक",
    adminLoginDesc: "हे पॅनेल फक्त नगरसेवकांसाठी आहे.",
    loginAsAdmin: "प्रशासक म्हणून लॉगिन करा",
    reportProblemTitle: "समस्या नोंदवा",
    yourComplaintGoes: "तुमची तक्रार थेट वॉर्ड अधिकाऱ्याकडे जाते",
    photoOfProblem: "समस्येचा फोटो",
    takePhoto: "फोटो काढा",
    clickPhotoOfProblem: "समस्येचा फोटो काढा",
    chooseFromGallery: "गॅलरीतून निवडा",
    retake: "पुन्हा काढा",
    complaintCategory: "तक्रार श्रेणी",
    complaintTitle: "तक्रार शीर्षक",
    titlePlaceholder: "उदा: मुख्य रस्त्यावर मोठा खड्डा",
    description: "वर्णन",
    descriptionPlaceholder: "समस्येचे तपशीलवार वर्णन करा — ठिकाण, तीव्रता, किती दिवसांपासून...",
    location: "ठिकाण",
    enterExactLocation: "नेमके ठिकाण टाका",
    autoDetected: "स्वयं शोधले",
    complaintNotice: "तुमची तक्रार 24 तासांच्या आत वॉर्ड अधिकाऱ्याला सोपवली जाईल. तुम्हाला येथे स्थिती अपडेट मिळतील.",
    submitComplaint: "तक्रार सबमिट करा",
    selectCategoryAlert: "श्रेणी निवडा",
    selectCategoryMsg: "कृपया तक्रार श्रेणी निवडा.",
    addTitleAlert: "शीर्षक जोडा",
    addTitleMsg: "कृपया तुमच्या तक्रारीसाठी संक्षिप्त शीर्षक जोडा.",
    addDescAlert: "वर्णन जोडा",
    addDescMsg: "कृपया समस्येचे वर्णन करा.",
    permissionNeeded: "परवानगी आवश्यक",
    cameraPermission: "समस्येचा फोटो काढण्यासाठी कॅमेरा एक्सेस आवश्यक आहे.",
    complaintRegistered: "तक्रार नोंदवली गेली!",
    complaintStatus: "तक्रार स्थिती",
    complaintDetails: "तक्रार तपशील",
    category: "श्रेणी",
    submittedOn: "सबमिट केल्याची तारीख",
    assignedTo: "यांना सोपवले",
    activityTimeline: "गतिविधी टाइमलाइन",
    problemPhoto: "समस्येचा फोटो",
    complaintNotFound: "तक्रार सापडली नाही",
    issueResolved: "समस्या सोडवली",
    policeStations: "पोलीस स्टेशन",
    banksATMs: "बँका आणि ATM",
    postOffices: "टपालघर",
    crematoriums: "शमशानभूमी",
    updated: "अपडेटेड",
    enterFullName: "तुमचे पूर्ण नाव टाका",
    enterValidAge: "वैध वय टाका (1–120)",
    enterValidEmail: "वैध ईमेल पत्ता टाका",
    enterAddress: "तुमचा पत्ता टाका",
    enterValidPhone: "वैध 10-अंकी फोन नंबर टाका",
    selectWardError: "कृपया तुमचा वॉर्ड निवडा",
    enterOtp: "4-अंकी OTP टाका",
    otpVerification: "OTP सत्यापन",
    otpSent: "OTP पाठवले",
    otpHint: "डेमोसाठी कोणतेही 4 अंक वापरा",
    verifyOtp: "OTP सत्यापित करा",
    phoneVerified: "फोन सत्यापित!",
    allowNotifications: "तुम्हाला अपडेट कसे मिळायला हवेत?",
    emailNotifications: "ईमेल सूचना",
    emailNotifDesc: "ईमेलद्वारे तक्रार अपडेट मिळवा",
    whatsappNotifications: "WhatsApp सूचना",
    whatsappNotifDesc: "WhatsApp वर अपडेट मिळवा",
    registerBtn: "नोंदणी करा",
    loginBtn: "लॉगिन",
    registrationSuccess: "नोंदणी यशस्वी!",
    registrationFailed: "नोंदणी अयशस्वी. पुन्हा प्रयत्न करा.",
    redirectingHome: "होमवर जात आहे...",
    invalidNagarsevakId: "अवैध नगरसेवक ID",
    accountNotFound: "खाते सापडले नाही. कृपया आधी नोंदणी करा.",
    nagarsevakIdLabel: "नगरसेवक ID",
    nagarsevakIdPlaceholder: "उदा. NS001",
    nagarsevakIdHelp: "अधिकारी पॅनेल ॲक्सेस करण्यासाठी तुमचा नगरसेवक ID टाका",
    currentAddress: "पत्ता",
    phoneNumber: "फोन नंबर",
    enterPhoneNumber: "फोन नंबर टाका",
    enterAge: "वय टाका",
    nagarsevakOnly: "फक्त नगरसेवक प्रवेश",
    nagarsevakOnlyDesc: "हे पॅनेल फक्त नगरसेवकांसाठी आहे. प्रवेशासाठी तुमच्या नगरसेवक ID ने लॉगिन करा.",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
}

const LANG_KEY = "janseva_language";

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLang] = useState<Language>("en");

  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY).then((stored) => {
      if (stored && (stored === "en" || stored === "hi" || stored === "mr")) {
        setLang(stored as Language);
      }
    });
  }, []);

  const setLanguage = async (lang: Language) => {
    setLang(lang);
    await AsyncStorage.setItem(LANG_KEY, lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] ?? translations.en[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be inside LanguageProvider");
  return ctx;
}
